package br.com.banctec.tela.login;

import java.awt.Toolkit;
import java.awt.Desktop;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.net.URI;
import org.springframework.jdbc.core.JdbcTemplate;
import tabelas.TbUsDados;
import jdbc.Conexao;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.springframework.jdbc.core.BeanPropertyRowMapper;

/**
 *
 * @author Pinheiro
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashDev = new javax.swing.JFrame();
        DashDevTela = new javax.swing.JDesktopPane();
        TelaDashDev = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jblEscolha = new javax.swing.JLabel();
        jblNomeDev = new javax.swing.JLabel();
        jblLogo1 = new javax.swing.JLabel();
        btnEclipse = new javax.swing.JButton();
        btnPyCharm = new javax.swing.JButton();
        btnPhpStorm = new javax.swing.JButton();
        btnXcode = new javax.swing.JButton();
        btnIntellij = new javax.swing.JButton();
        btnEclipse5 = new javax.swing.JButton();
        btnEclipse6 = new javax.swing.JButton();
        btnXcode1 = new javax.swing.JButton();
        btnPhpStorm1 = new javax.swing.JButton();
        btnIntellij1 = new javax.swing.JButton();
        btnEclipse1 = new javax.swing.JButton();
        btnPyCharm1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnTurorials = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnHome9 = new javax.swing.JButton();
        jblMneuDev = new javax.swing.JLabel();
        DashGestor = new javax.swing.JFrame();
        TelaDashGestor = new javax.swing.JDesktopPane();
        jpFundo = new javax.swing.JPanel();
        jblBemVindo = new javax.swing.JLabel();
        jblMaquinaa = new javax.swing.JLabel();
        jblNomeGestor = new javax.swing.JLabel();
        btnMaquina1 = new javax.swing.JButton();
        jblLogo = new javax.swing.JLabel();
        btnMaquina5 = new javax.swing.JButton();
        btnMaquina6 = new javax.swing.JButton();
        btnMaquina7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSettingsGestor = new javax.swing.JButton();
        btnProfileGestor = new javax.swing.JButton();
        btnLogoutGestor = new javax.swing.JButton();
        btnTutorialsGestor = new javax.swing.JButton();
        btnHomeGestor = new javax.swing.JButton();
        jblMenu = new javax.swing.JLabel();
        btnMaquina8 = new javax.swing.JButton();
        btnMaquina9 = new javax.swing.JButton();
        TelaLogin = new javax.swing.JDesktopPane();
        background = new javax.swing.JPanel();
        cardLogin = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        lblValida = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblTitleLogin = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();

        DashDev.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TelaDashDev.setBackground(new java.awt.Color(206, 228, 217));
        TelaDashDev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TelaDashDev.setPreferredSize(new java.awt.Dimension(1366, 720));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Bem Vindo,");

        jblEscolha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblEscolha.setForeground(new java.awt.Color(102, 102, 102));
        jblEscolha.setText("Escolha as IDE's que serão monitoradas");

        jblNomeDev.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblNomeDev.setForeground(new java.awt.Color(102, 102, 102));
        jblNomeDev.setText("nome");

        jblLogo1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo1.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo1.setText("KEEPCODE");

        btnEclipse.setBackground(new java.awt.Color(255, 255, 255));
        btnEclipse.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEclipse.setText("ECLIPSE");
        btnEclipse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPyCharm.setBackground(new java.awt.Color(255, 255, 255));
        btnPyCharm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPyCharm.setText("PYCHARM");
        btnPyCharm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPhpStorm.setBackground(new java.awt.Color(255, 255, 255));
        btnPhpStorm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPhpStorm.setText("PHPSTORM");
        btnPhpStorm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnXcode.setBackground(new java.awt.Color(255, 255, 255));
        btnXcode.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXcode.setText("XCODE");
        btnXcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIntellij.setBackground(new java.awt.Color(255, 255, 255));
        btnIntellij.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIntellij.setText("INTELLIJ");
        btnIntellij.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEclipse5.setBackground(new java.awt.Color(255, 255, 255));
        btnEclipse5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEclipse5.setText("ECLIPSE");
        btnEclipse5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnEclipse6.setBackground(new java.awt.Color(255, 255, 255));
        btnEclipse6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEclipse6.setText("ECLIPSE");
        btnEclipse6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnXcode1.setBackground(new java.awt.Color(255, 255, 255));
        btnXcode1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXcode1.setText("XCODE");
        btnXcode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPhpStorm1.setBackground(new java.awt.Color(255, 255, 255));
        btnPhpStorm1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPhpStorm1.setText("PHPSTORM");
        btnPhpStorm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIntellij1.setBackground(new java.awt.Color(255, 255, 255));
        btnIntellij1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIntellij1.setText("VSCODE");
        btnIntellij1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIntellij1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntellij1ActionPerformed(evt);
            }
        });

        btnEclipse1.setBackground(new java.awt.Color(255, 255, 255));
        btnEclipse1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEclipse1.setText("ECLIPSE");
        btnEclipse1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnPyCharm1.setBackground(new java.awt.Color(255, 255, 255));
        btnPyCharm1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPyCharm1.setText("PYCHARM");
        btnPyCharm1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(110, 150, 146));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(183, 51, 73));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(183, 51, 73));
        btnSettings.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSettings.setText("Settings");
        btnSettings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnTurorials.setBackground(new java.awt.Color(183, 51, 73));
        btnTurorials.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTurorials.setForeground(new java.awt.Color(255, 255, 255));
        btnTurorials.setText("Tutorials");
        btnTurorials.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTurorials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurorialsActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(183, 51, 73));
        btnProfile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("Profile");
        btnProfile.setToolTipText("");
        btnProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfile.setPreferredSize(new java.awt.Dimension(45, 25));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnHome9.setBackground(new java.awt.Color(183, 51, 73));
        btnHome9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome9.setForeground(new java.awt.Color(255, 255, 255));
        btnHome9.setText("Home");
        btnHome9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome9.setName(""); // NOI18N
        btnHome9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome9ActionPerformed(evt);
            }
        });

        jblMneuDev.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout)
                            .addComponent(btnTurorials)
                            .addComponent(btnSettings)
                            .addComponent(btnHome9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jblMneuDev)
                        .addGap(56, 56, 56))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHome9, btnLogout, btnProfile, btnSettings, btnTurorials});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jblMneuDev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnHome9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnTurorials)
                .addGap(35, 35, 35)
                .addComponent(btnSettings)
                .addGap(29, 29, 29)
                .addComponent(btnLogout)
                .addGap(30, 30, 30))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHome9, btnLogout, btnProfile, btnSettings, btnTurorials});

        javax.swing.GroupLayout TelaDashDevLayout = new javax.swing.GroupLayout(TelaDashDev);
        TelaDashDev.setLayout(TelaDashDevLayout);
        TelaDashDevLayout.setHorizontalGroup(
            TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaDashDevLayout.createSequentialGroup()
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblLogo1)
                            .addGroup(TelaDashDevLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108)
                                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPhpStorm)
                                    .addComponent(btnIntellij, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnXcode)
                                    .addComponent(btnEclipse))
                                .addGap(54, 54, 54)
                                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPyCharm)
                                    .addComponent(btnEclipse5))
                                .addGap(53, 53, 53)
                                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIntellij1)
                                    .addComponent(btnPhpStorm1))
                                .addGap(59, 59, 59)
                                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXcode1)
                                    .addComponent(btnEclipse1))))
                        .addGap(70, 70, 70)
                        .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPyCharm1)
                            .addComponent(btnEclipse6)))
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGap(523, 523, 523)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jblNomeDev))
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(jblEscolha)))
                .addContainerGap(222, Short.MAX_VALUE))
        );

        TelaDashDevLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEclipse, btnEclipse1, btnEclipse5, btnEclipse6, btnIntellij, btnIntellij1, btnPhpStorm, btnPhpStorm1, btnPyCharm, btnPyCharm1, btnXcode, btnXcode1});

        TelaDashDevLayout.setVerticalGroup(
            TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaDashDevLayout.createSequentialGroup()
                .addComponent(jblLogo1)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEclipse1)
                            .addComponent(btnPyCharm1))
                        .addGap(133, 133, 133)
                        .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPhpStorm1)
                            .addComponent(btnXcode1)
                            .addComponent(btnEclipse6)
                            .addComponent(btnPhpStorm)
                            .addComponent(btnXcode)
                            .addComponent(btnEclipse5)))
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jblNomeDev))
                        .addGap(60, 60, 60)
                        .addComponent(jblEscolha)
                        .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TelaDashDevLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnIntellij, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPyCharm)
                                    .addComponent(btnEclipse)
                                    .addComponent(btnIntellij1)))
                            .addGroup(TelaDashDevLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        TelaDashDevLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEclipse, btnEclipse1, btnEclipse5, btnEclipse6, btnIntellij, btnIntellij1, btnPhpStorm, btnPhpStorm1, btnPyCharm, btnPyCharm1, btnXcode, btnXcode1});

        DashDevTela.setLayer(TelaDashDev, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DashDevTelaLayout = new javax.swing.GroupLayout(DashDevTela);
        DashDevTela.setLayout(DashDevTelaLayout);
        DashDevTelaLayout.setHorizontalGroup(
            DashDevTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaDashDev, javax.swing.GroupLayout.DEFAULT_SIZE, 1401, Short.MAX_VALUE)
        );
        DashDevTelaLayout.setVerticalGroup(
            DashDevTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaDashDev, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        TelaDashDev.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout DashDevLayout = new javax.swing.GroupLayout(DashDev.getContentPane());
        DashDev.getContentPane().setLayout(DashDevLayout);
        DashDevLayout.setHorizontalGroup(
            DashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashDevTela)
        );
        DashDevLayout.setVerticalGroup(
            DashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashDevTela, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        DashGestor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        DashGestor.setBackground(new java.awt.Color(206, 228, 217));
        DashGestor.setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        DashGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DashGestor.setLocation(new java.awt.Point(0, 0));
        DashGestor.setMinimumSize(new java.awt.Dimension(1280, 720));
        DashGestor.setPreferredSize(new java.awt.Dimension(1401, 742));
        DashGestor.setSize(new java.awt.Dimension(0, 0));

        TelaDashGestor.setAutoscrolls(true);
        TelaDashGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TelaDashGestor.setInheritsPopupMenu(true);
        TelaDashGestor.setName(""); // NOI18N
        TelaDashGestor.setPreferredSize(new java.awt.Dimension(1401, 742));

        javax.swing.GroupLayout TelaDashGestorLayout = new javax.swing.GroupLayout(TelaDashGestor);
        TelaDashGestor.setLayout(TelaDashGestorLayout);
        TelaDashGestorLayout.setHorizontalGroup(
            TelaDashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TelaDashGestorLayout.setVerticalGroup(
            TelaDashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 742, Short.MAX_VALUE)
        );

        jpFundo.setBackground(new java.awt.Color(206, 228, 217));
        jpFundo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jpFundo.setPreferredSize(new java.awt.Dimension(1401, 742));

        jblBemVindo.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblBemVindo.setForeground(new java.awt.Color(102, 102, 102));
        jblBemVindo.setText("Bem Vindo,");

        jblMaquinaa.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblMaquinaa.setForeground(new java.awt.Color(102, 102, 102));
        jblMaquinaa.setText("Escolha a maquina de um funcionário");

        jblNomeGestor.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblNomeGestor.setForeground(new java.awt.Color(102, 102, 102));
        jblNomeGestor.setText("Nome");

        btnMaquina1.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina1.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina1.setText("VMNOTE - 144");
        btnMaquina1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina1ActionPerformed(evt);
            }
        });

        jblLogo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo.setText("KEEPCODE");

        btnMaquina5.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina5.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina5.setText("VMNOTE - 146");
        btnMaquina5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina5ActionPerformed(evt);
            }
        });

        btnMaquina6.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina6.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina6.setText("VMNOTE - 142");
        btnMaquina6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina6ActionPerformed(evt);
            }
        });

        btnMaquina7.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina7.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina7.setText("VMNOTE - 143");
        btnMaquina7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina7ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(110, 150, 146));

        btnSettingsGestor.setBackground(new java.awt.Color(183, 51, 73));
        btnSettingsGestor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSettingsGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnSettingsGestor.setText("Settings");
        btnSettingsGestor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSettingsGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsGestorActionPerformed(evt);
            }
        });

        btnProfileGestor.setBackground(new java.awt.Color(183, 51, 73));
        btnProfileGestor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnProfileGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnProfileGestor.setText("Profile");
        btnProfileGestor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfileGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileGestorActionPerformed(evt);
            }
        });

        btnLogoutGestor.setBackground(new java.awt.Color(183, 51, 73));
        btnLogoutGestor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogoutGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnLogoutGestor.setText("Logout");
        btnLogoutGestor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogoutGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutGestorActionPerformed(evt);
            }
        });

        btnTutorialsGestor.setBackground(new java.awt.Color(183, 51, 73));
        btnTutorialsGestor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTutorialsGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnTutorialsGestor.setText("Tutorials");
        btnTutorialsGestor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTutorialsGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutorialsGestorActionPerformed(evt);
            }
        });

        btnHomeGestor.setBackground(new java.awt.Color(183, 51, 73));
        btnHomeGestor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHomeGestor.setForeground(new java.awt.Color(255, 255, 255));
        btnHomeGestor.setText("Home");
        btnHomeGestor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHomeGestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeGestorActionPerformed(evt);
            }
        });

        jblMenu.setText("Menu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSettingsGestor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTutorialsGestor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProfileGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLogoutGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnHomeGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jblMenu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHomeGestor, btnLogoutGestor, btnProfileGestor, btnSettingsGestor, btnTutorialsGestor});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jblMenu)
                .addGap(9, 9, 9)
                .addComponent(btnHomeGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfileGestor)
                .addGap(32, 32, 32)
                .addComponent(btnTutorialsGestor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnSettingsGestor)
                .addGap(29, 29, 29)
                .addComponent(btnLogoutGestor)
                .addGap(24, 24, 24))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHomeGestor, btnLogoutGestor, btnProfileGestor, btnSettingsGestor, btnTutorialsGestor});

        btnMaquina8.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina8.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina8.setText("VMNOTE - 145");
        btnMaquina8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina8ActionPerformed(evt);
            }
        });

        btnMaquina9.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina9.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina9.setText("VMNOTE - 141");
        btnMaquina9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFundoLayout = new javax.swing.GroupLayout(jpFundo);
        jpFundo.setLayout(jpFundoLayout);
        jpFundoLayout.setHorizontalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblLogo)
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jblBemVindo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblNomeGestor))))
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblMaquinaa)
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMaquina6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMaquina7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMaquina9, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMaquina1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpFundoLayout.createSequentialGroup()
                                        .addGap(278, 278, 278)
                                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnMaquina8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMaquina5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jpFundoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMaquina1, btnMaquina5, btnMaquina6, btnMaquina7});

        jpFundoLayout.setVerticalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jblMaquinaa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaquina1))
                .addGap(59, 59, 59)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaquina8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina5)
                    .addComponent(btnMaquina7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(139, 139, 139))
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblLogo)
                .addGap(12, 12, 12)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblBemVindo)
                    .addComponent(jblNomeGestor))
                .addGap(162, 162, 162)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jpFundoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMaquina1, btnMaquina5, btnMaquina6, btnMaquina7});

        javax.swing.GroupLayout DashGestorLayout = new javax.swing.GroupLayout(DashGestor.getContentPane());
        DashGestor.getContentPane().setLayout(DashGestorLayout);
        DashGestorLayout.setHorizontalGroup(
            DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashGestorLayout.createSequentialGroup()
                .addComponent(jpFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 1443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TelaDashGestor, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        DashGestorLayout.setVerticalGroup(
            DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashGestorLayout.createSequentialGroup()
                .addGroup(DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TelaDashGestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TelaDashGestor.getAccessibleContext().setAccessibleParent(this);
        jpFundo.getAccessibleContext().setAccessibleParent(TelaLogin);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));

        background.setBackground(new java.awt.Color(206, 228, 217));

        cardLogin.setBackground(new java.awt.Color(110, 150, 146));
        cardLogin.setForeground(new java.awt.Color(255, 102, 102));

        txtEmail.setBackground(new java.awt.Color(237, 230, 221));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(81, 78, 77));
        txtEmail.setText("Informe seu login aqui");
        txtEmail.setToolTipText("LOGIN");
        txtEmail.setNextFocusableComponent(txtSenha);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblValida.setBackground(new java.awt.Color(255, 51, 51));
        lblValida.setForeground(new java.awt.Color(255, 102, 102));
        lblValida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtSenha.setBackground(new java.awt.Color(237, 230, 221));
        txtSenha.setForeground(new java.awt.Color(81, 78, 77));
        txtSenha.setText("Senha123");
        txtSenha.setToolTipText("SENHA");
        txtSenha.setNextFocusableComponent(btnEntrar);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(136, 169, 167));
        btnEntrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorderPainted(false);
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblTitleLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleLogin.setForeground(new java.awt.Color(81, 78, 77));
        lblTitleLogin.setText("FAÇA O LOGIN");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(81, 78, 77));
        lblEmail.setText("Login:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(81, 78, 77));
        lblSenha.setText("Senha");

        javax.swing.GroupLayout cardLoginLayout = new javax.swing.GroupLayout(cardLogin);
        cardLogin.setLayout(cardLoginLayout);
        cardLoginLayout.setHorizontalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLoginLayout.createSequentialGroup()
                .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblSenha)
                            .addGroup(cardLoginLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitleLogin))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        cardLoginLayout.setVerticalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTitleLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        txtEmail.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(cardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(cardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        TelaLogin.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaLoginLayout = new javax.swing.GroupLayout(TelaLogin);
        TelaLogin.setLayout(TelaLoginLayout);
        TelaLoginLayout.setHorizontalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TelaLoginLayout.setVerticalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        Runtime.getRuntime().exit(0);
    }

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Conexao con = new Conexao();

        JdbcTemplate template = new JdbcTemplate(con.getBanco());

        List<TbUsDados> pegandoUser = template.query("SELECT us_login, us_senha, us_nome_funcionario, us_is_adm FROM tb_us_dados WHERE us_login = ? AND us_senha = ?",
                new BeanPropertyRowMapper<>(TbUsDados.class), txtEmail.getText(), txtSenha.getText());

        System.out.println(pegandoUser);

        String pegandoEmail = txtEmail.getText();
        String pegandoSenha = txtSenha.getText();

        String isAdmin = "1";

        if (pegandoUser.isEmpty()) {

            lblValida.setText("Email ou senha incorretos");
            txtEmail.setText("Informe seu login aqui");
            txtSenha.setText("Senha123");
        } else {
            if (pegandoUser.size() == 1) {

                for (Iterator<TbUsDados> it = pegandoUser.iterator(); it.hasNext();) {

                    TbUsDados tbUsDados = it.next();

                    if (tbUsDados.getUs_login().equals(pegandoEmail) && tbUsDados.getUs_senha().equals(pegandoSenha)) {

                        if (tbUsDados.getUs_is_adm().equals(isAdmin)) {
                            this.setVisible(false);
                            this.dispose();
                          //  GraphicsEnvironment graphics
                                //    = GraphicsEnvironment.getLocalGraphicsEnvironment();
                            
                           // GraphicsDevice device = graphics.getDefaultScreenDevice();
                            
                            DashGestor.setVisible(true);
                            jblNomeGestor.setText(tbUsDados.getUs_nome_funcionario());
                            
                          // device.setFullScreenWindow(DashGestor);
                        } else {
                            this.setVisible(false);
                            this.dispose();
                           
                            DashDev.setVisible(true);
                            jblNomeDev.setText(tbUsDados.getUs_nome_funcionario());
                             
                        }

                    }
                }

            } else if (pegandoUser.size() > 1) {
                txtEmail.setText("Informe seu login aqui");
                txtSenha.setText("Senha123");
                lblValida.setText("Email ou senha incorretos:\n Login já utilizado!");
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        // TODO add your handling code here:
        if (txtSenha.getText().equals("")) {
            txtSenha.setText("Senha123");
        }
    }//GEN-LAST:event_txtSenhaFocusLost

//  PLACEHOLDER CAMPO SENHA    
    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
        if (txtSenha.getText().equals("Senha123")) {
            txtSenha.setText("");
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Informe seu login aqui");
        }
    }//GEN-LAST:event_txtEmailFocusLost

//    PLACEHOLDER CAMPO EMAIL
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if (txtEmail.getText().equals("Informe seu login aqui")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void btnHomeGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeGestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeGestorActionPerformed

    private void btnTutorialsGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutorialsGestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutorialsGestorActionPerformed

    private void btnLogoutGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutGestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutGestorActionPerformed

    private void btnProfileGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileGestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileGestorActionPerformed

    private void btnSettingsGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsGestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingsGestorActionPerformed

    private void btnMaquina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina1ActionPerformed

    private void btnMaquina5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina5ActionPerformed

    private void btnMaquina6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina6ActionPerformed

    private void btnMaquina7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina7ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnTurorialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurorialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurorialsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnHome9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome9ActionPerformed

    private void btnIntellij1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntellij1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIntellij1ActionPerformed

    private void btnMaquina8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina8ActionPerformed

    private void btnMaquina9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DashDev;
    private javax.swing.JDesktopPane DashDevTela;
    private javax.swing.JFrame DashGestor;
    private javax.swing.JPanel TelaDashDev;
    private javax.swing.JDesktopPane TelaDashGestor;
    private javax.swing.JDesktopPane TelaLogin;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEclipse;
    private javax.swing.JButton btnEclipse1;
    private javax.swing.JButton btnEclipse5;
    private javax.swing.JButton btnEclipse6;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnHome9;
    private javax.swing.JButton btnHomeGestor;
    private javax.swing.JButton btnIntellij;
    private javax.swing.JButton btnIntellij1;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogoutGestor;
    private javax.swing.JButton btnMaquina1;
    private javax.swing.JButton btnMaquina5;
    private javax.swing.JButton btnMaquina6;
    private javax.swing.JButton btnMaquina7;
    private javax.swing.JButton btnMaquina8;
    private javax.swing.JButton btnMaquina9;
    private javax.swing.JButton btnPhpStorm;
    private javax.swing.JButton btnPhpStorm1;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnProfileGestor;
    private javax.swing.JButton btnPyCharm;
    private javax.swing.JButton btnPyCharm1;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSettingsGestor;
    private javax.swing.JButton btnTurorials;
    private javax.swing.JButton btnTutorialsGestor;
    private javax.swing.JButton btnXcode;
    private javax.swing.JButton btnXcode1;
    private javax.swing.JPanel cardLogin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jblBemVindo;
    private javax.swing.JLabel jblEscolha;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel jblLogo1;
    private javax.swing.JLabel jblMaquinaa;
    private javax.swing.JLabel jblMenu;
    private javax.swing.JLabel jblMneuDev;
    private javax.swing.JLabel jblNomeDev;
    private javax.swing.JLabel jblNomeGestor;
    private javax.swing.JPanel jpFundo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitleLogin;
    private javax.swing.JLabel lblValida;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
