package br.com.banctec.tela.login;

import java.awt.Toolkit;
import java.awt.Desktop;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.net.URI;
import org.springframework.jdbc.core.JdbcTemplate;
import tabelas.TbUsDados;
import jdbc.Conexao;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.springframework.jdbc.core.BeanPropertyRowMapper;

/**
 *
 * @author Pinheiro
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashDev = new javax.swing.JFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jblEscolha = new javax.swing.JLabel();
        jblNomeDev = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        btnTurorials = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnHome9 = new javax.swing.JButton();
        jblLogo1 = new javax.swing.JLabel();
        btnEclipse = new javax.swing.JButton();
        btnPyCharm = new javax.swing.JButton();
        btnPhpStorm = new javax.swing.JButton();
        btnXcode = new javax.swing.JButton();
        btnIntellij = new javax.swing.JButton();
        btnEclipse5 = new javax.swing.JButton();
        DashGestor = new javax.swing.JFrame();
        TelaDashGestor = new javax.swing.JDesktopPane();
        jpFundo = new javax.swing.JPanel();
        jblBemVindo = new javax.swing.JLabel();
        jblMaquinaa = new javax.swing.JLabel();
        jblNomeGestor = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnMaquina1 = new javax.swing.JButton();
        btnHome1 = new javax.swing.JButton();
        btnHome2 = new javax.swing.JButton();
        btnHome3 = new javax.swing.JButton();
        btnHome4 = new javax.swing.JButton();
        jblLogo = new javax.swing.JLabel();
        btnMaquina5 = new javax.swing.JButton();
        btnMaquina6 = new javax.swing.JButton();
        btnMaquina7 = new javax.swing.JButton();
        TelaLogin = new javax.swing.JDesktopPane();
        background = new javax.swing.JPanel();
        cardLogin = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        lblValida = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblTitleLogin = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();

        DashDev.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(206, 228, 217));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Bem Vindo,");

        jblEscolha.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblEscolha.setForeground(new java.awt.Color(102, 102, 102));
        jblEscolha.setText("Escolha sua IDE");

        jblNomeDev.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblNomeDev.setForeground(new java.awt.Color(102, 102, 102));
        jblNomeDev.setText("nome");

        btnLogout.setBackground(new java.awt.Color(183, 51, 73));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSettings.setBackground(new java.awt.Color(183, 51, 73));
        btnSettings.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSettings.setText("Settings");
        btnSettings.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        btnTurorials.setBackground(new java.awt.Color(183, 51, 73));
        btnTurorials.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTurorials.setForeground(new java.awt.Color(255, 255, 255));
        btnTurorials.setText("Tutorials");
        btnTurorials.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTurorials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurorialsActionPerformed(evt);
            }
        });

        btnProfile.setBackground(new java.awt.Color(183, 51, 73));
        btnProfile.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("Profile");
        btnProfile.setToolTipText("");
        btnProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfile.setPreferredSize(new java.awt.Dimension(45, 25));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnHome9.setBackground(new java.awt.Color(183, 51, 73));
        btnHome9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome9.setForeground(new java.awt.Color(255, 255, 255));
        btnHome9.setText("Home");
        btnHome9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome9.setName(""); // NOI18N
        btnHome9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome9ActionPerformed(evt);
            }
        });

        jblLogo1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo1.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo1.setText("KEEPCODE");

        btnEclipse.setText("ECLIPSE");

        btnPyCharm.setText("PYCHARM");

        btnPhpStorm.setText("PHPSTORM");

        btnXcode.setText("XCODE");

        btnIntellij.setText("INTELLIJ");

        btnEclipse5.setText("ECLIPSE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTurorials)
                            .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHome9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIntellij)
                            .addComponent(btnPhpStorm)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jblEscolha)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jblNomeDev))))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEclipse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(btnPyCharm)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEclipse5)
                        .addGap(55, 55, 55))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblLogo1)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jblLogo1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jblNomeDev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jblEscolha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnHome9)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEclipse)
                    .addComponent(btnIntellij)
                    .addComponent(btnPyCharm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnTurorials)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnSettings))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPhpStorm)
                            .addComponent(btnXcode)
                            .addComponent(btnEclipse5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(21, 21, 21))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout DashDevLayout = new javax.swing.GroupLayout(DashDev.getContentPane());
        DashDev.getContentPane().setLayout(DashDevLayout);
        DashDevLayout.setHorizontalGroup(
            DashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        DashDevLayout.setVerticalGroup(
            DashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        DashGestor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        DashGestor.setBackground(new java.awt.Color(206, 228, 217));
        DashGestor.setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        DashGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DashGestor.setLocation(new java.awt.Point(0, 0));
        DashGestor.setPreferredSize(new java.awt.Dimension(747, 456));
        DashGestor.setSize(new java.awt.Dimension(266, 300));

        TelaDashGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TelaDashGestor.setInheritsPopupMenu(true);
        TelaDashGestor.setPreferredSize(new java.awt.Dimension(747, 456));

        jpFundo.setBackground(new java.awt.Color(206, 228, 217));
        jpFundo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jpFundo.setPreferredSize(new java.awt.Dimension(735, 456));

        jblBemVindo.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblBemVindo.setForeground(new java.awt.Color(102, 102, 102));
        jblBemVindo.setText("Bem Vindo,");

        jblMaquinaa.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblMaquinaa.setForeground(new java.awt.Color(102, 102, 102));
        jblMaquinaa.setText("Escolha uma maquina");

        jblNomeGestor.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblNomeGestor.setForeground(new java.awt.Color(102, 102, 102));
        jblNomeGestor.setText("Nome");

        btnHome.setBackground(new java.awt.Color(183, 51, 73));
        btnHome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Settings");
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnMaquina1.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina1.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina1.setText("VMNOTE - 143");
        btnMaquina1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina1ActionPerformed(evt);
            }
        });

        btnHome1.setBackground(new java.awt.Color(183, 51, 73));
        btnHome1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(255, 255, 255));
        btnHome1.setText("Profile");
        btnHome1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });

        btnHome2.setBackground(new java.awt.Color(183, 51, 73));
        btnHome2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome2.setForeground(new java.awt.Color(255, 255, 255));
        btnHome2.setText("Logout");
        btnHome2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });

        btnHome3.setBackground(new java.awt.Color(183, 51, 73));
        btnHome3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome3.setForeground(new java.awt.Color(255, 255, 255));
        btnHome3.setText("Tutorials");
        btnHome3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome3ActionPerformed(evt);
            }
        });

        btnHome4.setBackground(new java.awt.Color(183, 51, 73));
        btnHome4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHome4.setForeground(new java.awt.Color(255, 255, 255));
        btnHome4.setText("Home");
        btnHome4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome4ActionPerformed(evt);
            }
        });

        jblLogo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo.setText("KEEPCODE");

        btnMaquina5.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina5.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina5.setText("VMNOTE - 144");
        btnMaquina5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina5ActionPerformed(evt);
            }
        });

        btnMaquina6.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina6.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina6.setText("VMNOTE - 141");
        btnMaquina6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina6ActionPerformed(evt);
            }
        });

        btnMaquina7.setBackground(new java.awt.Color(255, 255, 255));
        btnMaquina7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina7.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina7.setText("VMNOTE - 142");
        btnMaquina7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMaquina7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFundoLayout = new javax.swing.GroupLayout(jpFundo);
        jpFundo.setLayout(jpFundoLayout);
        jpFundoLayout.setHorizontalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(btnHome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addComponent(btnMaquina7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(btnMaquina5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addComponent(btnMaquina6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMaquina1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addComponent(jblBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblNomeGestor)
                        .addGap(37, 37, 37))
                    .addComponent(jblMaquinaa))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jblLogo)
                .addContainerGap())
        );
        jpFundoLayout.setVerticalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNomeGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jblMaquinaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnHome4)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnHome1))
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMaquina6)
                            .addComponent(btnMaquina1))))
                .addGap(32, 32, 32)
                .addComponent(btnHome3)
                .addGap(30, 30, 30)
                .addComponent(btnHome)
                .addGap(3, 3, 3)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina7)
                    .addComponent(btnMaquina5))
                .addGap(4, 4, 4)
                .addComponent(btnHome2)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        TelaDashGestor.setLayer(jpFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaDashGestorLayout = new javax.swing.GroupLayout(TelaDashGestor);
        TelaDashGestor.setLayout(TelaDashGestorLayout);
        TelaDashGestorLayout.setHorizontalGroup(
            TelaDashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        TelaDashGestorLayout.setVerticalGroup(
            TelaDashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpFundo.getAccessibleContext().setAccessibleParent(TelaLogin);

        javax.swing.GroupLayout DashGestorLayout = new javax.swing.GroupLayout(DashGestor.getContentPane());
        DashGestor.getContentPane().setLayout(DashGestorLayout);
        DashGestorLayout.setHorizontalGroup(
            DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashGestorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TelaDashGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DashGestorLayout.setVerticalGroup(
            DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashGestorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TelaDashGestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TelaDashGestor.getAccessibleContext().setAccessibleParent(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));

        background.setBackground(new java.awt.Color(206, 228, 217));

        cardLogin.setBackground(new java.awt.Color(110, 150, 146));
        cardLogin.setForeground(new java.awt.Color(255, 102, 102));

        txtEmail.setBackground(new java.awt.Color(237, 230, 221));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(81, 78, 77));
        txtEmail.setText("Informe seu login aqui");
        txtEmail.setToolTipText("LOGIN");
        txtEmail.setNextFocusableComponent(txtSenha);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblValida.setBackground(new java.awt.Color(255, 51, 51));
        lblValida.setForeground(new java.awt.Color(255, 102, 102));
        lblValida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtSenha.setBackground(new java.awt.Color(237, 230, 221));
        txtSenha.setForeground(new java.awt.Color(81, 78, 77));
        txtSenha.setText("Senha123");
        txtSenha.setToolTipText("SENHA");
        txtSenha.setNextFocusableComponent(btnEntrar);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(136, 169, 167));
        btnEntrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorderPainted(false);
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblTitleLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleLogin.setForeground(new java.awt.Color(81, 78, 77));
        lblTitleLogin.setText("FAÇA O LOGIN");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(81, 78, 77));
        lblEmail.setText("Login:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(81, 78, 77));
        lblSenha.setText("Senha");

        javax.swing.GroupLayout cardLoginLayout = new javax.swing.GroupLayout(cardLogin);
        cardLogin.setLayout(cardLoginLayout);
        cardLoginLayout.setHorizontalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLoginLayout.createSequentialGroup()
                .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblSenha)
                            .addGroup(cardLoginLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitleLogin))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        cardLoginLayout.setVerticalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTitleLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        txtEmail.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(cardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(cardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        TelaLogin.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaLoginLayout = new javax.swing.GroupLayout(TelaLogin);
        TelaLogin.setLayout(TelaLoginLayout);
        TelaLoginLayout.setHorizontalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TelaLoginLayout.setVerticalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        Runtime.getRuntime().exit(0);
    }

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Conexao con = new Conexao();

        JdbcTemplate template = new JdbcTemplate(con.getBanco());

        List<TbUsDados> pegandoUser = template.query("SELECT us_login, us_senha, us_nome_funcionario, us_is_adm FROM tb_us_dados WHERE us_login = ? AND us_senha = ?",
                new BeanPropertyRowMapper<>(TbUsDados.class), txtEmail.getText(), txtSenha.getText());

        System.out.println(pegandoUser);

        String pegandoEmail = txtEmail.getText();
        String pegandoSenha = txtSenha.getText();

        String isAdmin = "1";

        if (pegandoUser.isEmpty()) {

            lblValida.setText("Email ou senha incorretos");
            txtEmail.setText("Informe seu login aqui");
            txtSenha.setText("Senha123");
        } else {
            if (pegandoUser.size() == 1) {

                for (Iterator<TbUsDados> it = pegandoUser.iterator(); it.hasNext();) {

                    TbUsDados tbUsDados = it.next();

                    if (tbUsDados.getUs_login().equals(pegandoEmail) && tbUsDados.getUs_senha().equals(pegandoSenha)) {

                        if (tbUsDados.getUs_is_adm().equals(isAdmin)) {
                            this.setVisible(false);
                            this.dispose();
                            
                            GraphicsEnvironment graphics
                                    = GraphicsEnvironment.getLocalGraphicsEnvironment();
                            
                            GraphicsDevice device = graphics.getDefaultScreenDevice();
                            
                            DashGestor.setVisible(true);
                            jblNomeGestor.setText(tbUsDados.getUs_nome_funcionario());
                            
//                            device.setFullScreenWindow(DashGestor);
                        } else {
                            this.setVisible(false);
                            this.dispose();
                            DashDev.setVisible(true);
                            jblNomeDev.setText(tbUsDados.getUs_nome_funcionario());
                        }

                    }
                }

            } else if (pegandoUser.size() > 1) {
                txtEmail.setText("Informe seu login aqui");
                txtSenha.setText("Senha123");
                lblValida.setText("Email ou senha incorretos:\n Login já utilizado!");
            }
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        // TODO add your handling code here:
        if (txtSenha.getText().equals("")) {
            txtSenha.setText("Senha123");
        }
    }//GEN-LAST:event_txtSenhaFocusLost

//  PLACEHOLDER CAMPO SENHA    
    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
        if (txtSenha.getText().equals("Senha123")) {
            txtSenha.setText("");
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Informe seu login aqui");
        }
    }//GEN-LAST:event_txtEmailFocusLost

//    PLACEHOLDER CAMPO EMAIL
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if (txtEmail.getText().equals("Informe seu login aqui")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void btnHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome4ActionPerformed

    private void btnHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome3ActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome1ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnMaquina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina1ActionPerformed

    private void btnMaquina5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina5ActionPerformed

    private void btnMaquina6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina6ActionPerformed

    private void btnMaquina7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaquina7ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnTurorialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurorialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTurorialsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnHome9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaLogin().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame DashDev;
    private javax.swing.JFrame DashGestor;
    private javax.swing.JDesktopPane TelaDashGestor;
    private javax.swing.JDesktopPane TelaLogin;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnEclipse;
    private javax.swing.JButton btnEclipse5;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome1;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnHome3;
    private javax.swing.JButton btnHome4;
    private javax.swing.JButton btnHome9;
    private javax.swing.JButton btnIntellij;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaquina1;
    private javax.swing.JButton btnMaquina5;
    private javax.swing.JButton btnMaquina6;
    private javax.swing.JButton btnMaquina7;
    private javax.swing.JButton btnPhpStorm;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnPyCharm;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnTurorials;
    private javax.swing.JButton btnXcode;
    private javax.swing.JPanel cardLogin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblBemVindo;
    private javax.swing.JLabel jblEscolha;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel jblLogo1;
    private javax.swing.JLabel jblMaquinaa;
    private javax.swing.JLabel jblNomeDev;
    private javax.swing.JLabel jblNomeGestor;
    private javax.swing.JPanel jpFundo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTitleLogin;
    private javax.swing.JLabel lblValida;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
