package com.mycompany.projeto.java;

import java.awt.AWTException;
import java.awt.Toolkit;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.math.BigInteger;
import org.springframework.jdbc.core.JdbcTemplate;
import jdbc.Conexao;
import java.util.List;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import org.springframework.jdbc.core.BeanPropertyRowMapper;
import tabelas.TbProcessosIde;
import log.GerandoLog;
import tabelas.TbUsMaquinaIdMaquina;
import AppKeepCode.KeepCodeAPI;

/**
 *
 * @author Pinheiro
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public static Long cpfDev = 15000000000L;
    public static Long cpfGestor = 15000000000L;

    BigInteger bigCpfDev = BigInteger.valueOf(cpfDev);
    BigInteger BigCpfGestor = BigInteger.valueOf(cpfGestor);

    public TelaLogin() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DashGestor = new javax.swing.JFrame();
        TelaDashGestor = new javax.swing.JDesktopPane();
        jpFundo = new javax.swing.JPanel();
        jblBemVindo = new javax.swing.JLabel();
        jblMaquinaa = new javax.swing.JLabel();
        jblNomeGestor = new javax.swing.JLabel();
        btnMaquina1 = new javax.swing.JButton();
        jblLogo = new javax.swing.JLabel();
        btnMaquina6 = new javax.swing.JButton();
        btnMaquina2 = new javax.swing.JButton();
        btnMaquina3 = new javax.swing.JButton();
        btnMaquina5 = new javax.swing.JButton();
        btnMaquina4 = new javax.swing.JButton();
        lblGestorEquipe = new javax.swing.JLabel();
        DashDev = new javax.swing.JFrame();
        DashDevTela = new javax.swing.JDesktopPane();
        TelaDashDev = new javax.swing.JPanel();
        jblEscolha = new javax.swing.JLabel();
        jblNomeDev = new javax.swing.JLabel();
        jblLogo1 = new javax.swing.JLabel();
        btnEclipse = new javax.swing.JButton();
        btnPyCharm = new javax.swing.JButton();
        btnPhpStorm = new javax.swing.JButton();
        btnXcode = new javax.swing.JButton();
        btnIntellij = new javax.swing.JButton();
        btnWebStorm = new javax.swing.JButton();
        btnVsCode = new javax.swing.JButton();
        btnNetBeans = new javax.swing.JButton();
        btnVisualStudio = new javax.swing.JButton();
        btnAndorid = new javax.swing.JButton();
        jblEmpresa = new javax.swing.JLabel();
        jblEquipe = new javax.swing.JLabel();
        jblCargo = new javax.swing.JLabel();
        jblEquipe1 = new javax.swing.JLabel();
        DetalheDev = new javax.swing.JFrame();
        DashDetalhesDev = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jblLogo2 = new javax.swing.JLabel();
        lblNomeIdeDtelhes = new javax.swing.JLabel();
        lblDiscoDev = new javax.swing.JLabel();
        lblCpuDev = new javax.swing.JLabel();
        lblRamDev = new javax.swing.JLabel();
        lblTempoUsoDev = new javax.swing.JLabel();
        lblgrafico = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNomeIde = new javax.swing.JLabel();
        TelaLogin = new javax.swing.JDesktopPane();
        background = new javax.swing.JPanel();
        cardLogin = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        lblValida = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblTitleLogin = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();

        DashGestor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        DashGestor.setAlwaysOnTop(true);
        DashGestor.setBackground(new java.awt.Color(206, 228, 217));
        DashGestor.setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        DashGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DashGestor.setIconImages(null);
        DashGestor.setLocation(new java.awt.Point(0, 0));
        DashGestor.setMinimumSize(new java.awt.Dimension(1280, 720));
        DashGestor.setSize(new java.awt.Dimension(0, 0));

        TelaDashGestor.setAutoscrolls(true);
        TelaDashGestor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TelaDashGestor.setInheritsPopupMenu(true);
        TelaDashGestor.setName(""); // NOI18N
        TelaDashGestor.setPreferredSize(new java.awt.Dimension(1401, 742));

        jpFundo.setBackground(new java.awt.Color(206, 228, 217));
        jpFundo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jpFundo.setPreferredSize(new java.awt.Dimension(1401, 742));

        jblBemVindo.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblBemVindo.setForeground(new java.awt.Color(102, 102, 102));
        jblBemVindo.setText("Bem Vindo,");

        jblMaquinaa.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblMaquinaa.setForeground(new java.awt.Color(102, 102, 102));
        jblMaquinaa.setText("Equipe:");

        jblNomeGestor.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        jblNomeGestor.setForeground(new java.awt.Color(102, 102, 102));
        jblNomeGestor.setText("Nome");

        btnMaquina1.setBackground(new java.awt.Color(206, 228, 217));
        btnMaquina1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina1.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solucao-part1_3_1.png"))); // NOI18N
        btnMaquina1.setText("VMNOTE - 141");
        btnMaquina1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMaquina1.setBorderPainted(false);
        btnMaquina1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaquina1.setMaximumSize(new java.awt.Dimension(105, 88));
        btnMaquina1.setPreferredSize(new java.awt.Dimension(105, 88));
        btnMaquina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina1ActionPerformed(evt);
            }
        });

        jblLogo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo.setText("KEEPCODE");

        btnMaquina6.setBackground(new java.awt.Color(206, 228, 217));
        btnMaquina6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina6.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solucao-part1_3_1.png"))); // NOI18N
        btnMaquina6.setText("VMNOTE - 146");
        btnMaquina6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMaquina6.setBorderPainted(false);
        btnMaquina6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaquina6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina6ActionPerformed(evt);
            }
        });

        btnMaquina2.setBackground(new java.awt.Color(206, 228, 217));
        btnMaquina2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina2.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solucao-part1_3_1.png"))); // NOI18N
        btnMaquina2.setText("VMNOTE - 142");
        btnMaquina2.setBorder(null);
        btnMaquina2.setBorderPainted(false);
        btnMaquina2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaquina2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina2ActionPerformed(evt);
            }
        });

        btnMaquina3.setBackground(new java.awt.Color(206, 228, 217));
        btnMaquina3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina3.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solucao-part1_3_1.png"))); // NOI18N
        btnMaquina3.setText("VMNOTE - 143");
        btnMaquina3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMaquina3.setBorderPainted(false);
        btnMaquina3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaquina3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina3ActionPerformed(evt);
            }
        });

        btnMaquina5.setBackground(new java.awt.Color(206, 228, 217));
        btnMaquina5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina5.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solucao-part1_3_1.png"))); // NOI18N
        btnMaquina5.setText("VMNOTE - 145");
        btnMaquina5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMaquina5.setBorderPainted(false);
        btnMaquina5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaquina5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina5ActionPerformed(evt);
            }
        });

        btnMaquina4.setBackground(new java.awt.Color(206, 228, 217));
        btnMaquina4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnMaquina4.setForeground(new java.awt.Color(0, 0, 0));
        btnMaquina4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solucao-part1_3_1.png"))); // NOI18N
        btnMaquina4.setText("VMNOTE - 144");
        btnMaquina4.setBorder(null);
        btnMaquina4.setBorderPainted(false);
        btnMaquina4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaquina4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquina4ActionPerformed(evt);
            }
        });

        lblGestorEquipe.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        lblGestorEquipe.setForeground(new java.awt.Color(102, 102, 102));
        lblGestorEquipe.setText("NOME DA EQUIPE");

        javax.swing.GroupLayout jpFundoLayout = new javax.swing.GroupLayout(jpFundo);
        jpFundo.setLayout(jpFundoLayout);
        jpFundoLayout.setHorizontalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFundoLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addComponent(jblBemVindo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jblNomeGestor))
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMaquina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaquina2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMaquina3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(443, 443, 443)
                                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMaquina5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMaquina4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMaquina6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpFundoLayout.createSequentialGroup()
                                .addGap(382, 382, 382)
                                .addComponent(jblMaquinaa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGestorEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jblLogo))
                .addContainerGap(363, Short.MAX_VALUE))
        );

        jpFundoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMaquina1, btnMaquina2, btnMaquina3, btnMaquina4, btnMaquina5, btnMaquina6});

        jpFundoLayout.setVerticalGroup(
            jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblLogo)
                .addGap(12, 12, 12)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblBemVindo)
                    .addComponent(jblNomeGestor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblMaquinaa, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGestorEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaquina4))
                .addGap(73, 73, 73)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaquina5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jpFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMaquina6)
                    .addComponent(btnMaquina3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpFundoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMaquina1, btnMaquina2, btnMaquina3, btnMaquina4, btnMaquina5, btnMaquina6});

        TelaDashGestor.setLayer(jpFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaDashGestorLayout = new javax.swing.GroupLayout(TelaDashGestor);
        TelaDashGestor.setLayout(TelaDashGestorLayout);
        TelaDashGestorLayout.setHorizontalGroup(
            TelaDashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaDashGestorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 1443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TelaDashGestorLayout.setVerticalGroup(
            TelaDashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaDashGestorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpFundo.getAccessibleContext().setAccessibleParent(TelaLogin);

        javax.swing.GroupLayout DashGestorLayout = new javax.swing.GroupLayout(DashGestor.getContentPane());
        DashGestor.getContentPane().setLayout(DashGestorLayout);
        DashGestorLayout.setHorizontalGroup(
            DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashGestorLayout.createSequentialGroup()
                .addComponent(TelaDashGestor, javax.swing.GroupLayout.DEFAULT_SIZE, 1395, Short.MAX_VALUE)
                .addContainerGap())
        );
        DashGestorLayout.setVerticalGroup(
            DashGestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashGestorLayout.createSequentialGroup()
                .addComponent(TelaDashGestor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TelaDashGestor.getAccessibleContext().setAccessibleParent(this);

        DashDev.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        DashDev.setLocation(new java.awt.Point(0, 0));
        DashDev.setMinimumSize(new java.awt.Dimension(1280, 720));
        DashDev.setSize(new java.awt.Dimension(0, 0));

        TelaDashDev.setBackground(new java.awt.Color(206, 228, 217));
        TelaDashDev.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TelaDashDev.setPreferredSize(new java.awt.Dimension(1366, 720));

        jblEscolha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblEscolha.setForeground(new java.awt.Color(102, 102, 102));
        jblEscolha.setText("Escolha  seu ambiente de desenvolvimento");

        jblNomeDev.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblNomeDev.setForeground(new java.awt.Color(102, 102, 102));
        jblNomeDev.setText("nome");

        jblLogo1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo1.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo1.setText("KEEPCODE");

        btnEclipse.setBackground(new java.awt.Color(206, 228, 217));
        btnEclipse.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnEclipse.setForeground(new java.awt.Color(0, 0, 0));
        btnEclipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eclipse_1.png"))); // NOI18N
        btnEclipse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEclipse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEclipse.setMaximumSize(new java.awt.Dimension(39, 23));
        btnEclipse.setMinimumSize(new java.awt.Dimension(39, 23));
        btnEclipse.setPreferredSize(new java.awt.Dimension(39, 23));
        btnEclipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEclipseActionPerformed(evt);
            }
        });

        btnPyCharm.setBackground(new java.awt.Color(206, 228, 217));
        btnPyCharm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPyCharm.setForeground(new java.awt.Color(0, 0, 0));
        btnPyCharm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pycharm_1_2.png"))); // NOI18N
        btnPyCharm.setBorder(null);
        btnPyCharm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPyCharm.setMaximumSize(new java.awt.Dimension(39, 23));
        btnPyCharm.setMinimumSize(new java.awt.Dimension(39, 23));
        btnPyCharm.setPreferredSize(new java.awt.Dimension(39, 23));
        btnPyCharm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPyCharmActionPerformed(evt);
            }
        });

        btnPhpStorm.setBackground(new java.awt.Color(206, 228, 217));
        btnPhpStorm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnPhpStorm.setForeground(new java.awt.Color(0, 0, 0));
        btnPhpStorm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phpstorm_1_2.png"))); // NOI18N
        btnPhpStorm.setBorder(null);
        btnPhpStorm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPhpStorm.setMaximumSize(new java.awt.Dimension(39, 23));
        btnPhpStorm.setMinimumSize(new java.awt.Dimension(39, 23));
        btnPhpStorm.setPreferredSize(new java.awt.Dimension(39, 23));
        btnPhpStorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhpStormActionPerformed(evt);
            }
        });

        btnXcode.setBackground(new java.awt.Color(206, 228, 217));
        btnXcode.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnXcode.setForeground(new java.awt.Color(0, 0, 0));
        btnXcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xcode_1.png"))); // NOI18N
        btnXcode.setBorder(null);
        btnXcode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXcode.setMaximumSize(new java.awt.Dimension(39, 23));
        btnXcode.setMinimumSize(new java.awt.Dimension(39, 23));
        btnXcode.setPreferredSize(new java.awt.Dimension(39, 23));
        btnXcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXcodeActionPerformed(evt);
            }
        });

        btnIntellij.setBackground(new java.awt.Color(206, 228, 217));
        btnIntellij.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIntellij.setForeground(new java.awt.Color(0, 0, 0));
        btnIntellij.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intellj_1.png"))); // NOI18N
        btnIntellij.setBorder(null);
        btnIntellij.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntellij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntellijActionPerformed(evt);
            }
        });

        btnWebStorm.setBackground(new java.awt.Color(206, 228, 217));
        btnWebStorm.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnWebStorm.setForeground(new java.awt.Color(0, 0, 0));
        btnWebStorm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/webstorm_1_1.png"))); // NOI18N
        btnWebStorm.setBorder(null);
        btnWebStorm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnWebStorm.setMaximumSize(new java.awt.Dimension(39, 23));
        btnWebStorm.setMinimumSize(new java.awt.Dimension(39, 23));
        btnWebStorm.setPreferredSize(new java.awt.Dimension(39, 23));
        btnWebStorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebStormActionPerformed(evt);
            }
        });

        btnVsCode.setBackground(new java.awt.Color(206, 228, 217));
        btnVsCode.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnVsCode.setForeground(new java.awt.Color(0, 0, 0));
        btnVsCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/code.png"))); // NOI18N
        btnVsCode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVsCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVsCode.setMaximumSize(new java.awt.Dimension(39, 23));
        btnVsCode.setMinimumSize(new java.awt.Dimension(39, 23));
        btnVsCode.setPreferredSize(new java.awt.Dimension(39, 23));
        btnVsCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVsCodeActionPerformed(evt);
            }
        });

        btnNetBeans.setBackground(new java.awt.Color(206, 228, 217));
        btnNetBeans.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNetBeans.setForeground(new java.awt.Color(0, 0, 0));
        btnNetBeans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/netbeans_1.png"))); // NOI18N
        btnNetBeans.setBorder(null);
        btnNetBeans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNetBeans.setMaximumSize(new java.awt.Dimension(39, 23));
        btnNetBeans.setMinimumSize(new java.awt.Dimension(39, 23));
        btnNetBeans.setPreferredSize(new java.awt.Dimension(39, 23));
        btnNetBeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetBeansActionPerformed(evt);
            }
        });

        btnVisualStudio.setBackground(new java.awt.Color(206, 228, 217));
        btnVisualStudio.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnVisualStudio.setForeground(new java.awt.Color(0, 0, 0));
        btnVisualStudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visualstudio_1_2.png"))); // NOI18N
        btnVisualStudio.setBorder(null);
        btnVisualStudio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVisualStudio.setMaximumSize(new java.awt.Dimension(39, 23));
        btnVisualStudio.setMinimumSize(new java.awt.Dimension(39, 23));
        btnVisualStudio.setPreferredSize(new java.awt.Dimension(39, 23));
        btnVisualStudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualStudioActionPerformed(evt);
            }
        });

        btnAndorid.setBackground(new java.awt.Color(206, 228, 217));
        btnAndorid.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnAndorid.setForeground(new java.awt.Color(0, 0, 0));
        btnAndorid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/androidstudio_1.png"))); // NOI18N
        btnAndorid.setBorder(null);
        btnAndorid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAndorid.setMaximumSize(new java.awt.Dimension(39, 23));
        btnAndorid.setMinimumSize(new java.awt.Dimension(39, 23));
        btnAndorid.setPreferredSize(new java.awt.Dimension(39, 23));
        btnAndorid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndoridActionPerformed(evt);
            }
        });

        jblEmpresa.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        jblEmpresa.setText("empresa");

        jblEquipe.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblEquipe.setForeground(new java.awt.Color(102, 102, 102));
        jblEquipe.setText("equipe");

        jblCargo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblCargo.setForeground(new java.awt.Color(102, 102, 102));
        jblCargo.setText("cargo");

        jblEquipe1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jblEquipe1.setForeground(new java.awt.Color(102, 102, 102));
        jblEquipe1.setText("nome maquina");

        javax.swing.GroupLayout TelaDashDevLayout = new javax.swing.GroupLayout(TelaDashDev);
        TelaDashDev.setLayout(TelaDashDevLayout);
        TelaDashDevLayout.setHorizontalGroup(
            TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaDashDevLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXcode, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEclipse, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPhpStorm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntellij, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPyCharm, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWebStorm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVisualStudio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnAndorid, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVsCode, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TelaDashDevLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnNetBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(421, 421, 421))
            .addGroup(TelaDashDevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblLogo1)
                .addGap(306, 306, 306))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaDashDevLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblNomeDev)
                    .addComponent(jblEquipe1)
                    .addComponent(jblEquipe)
                    .addComponent(jblEmpresa)
                    .addComponent(jblCargo)
                    .addComponent(jblEscolha))
                .addGap(557, 557, 557))
        );

        TelaDashDevLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnVisualStudio, btnVsCode});

        TelaDashDevLayout.setVerticalGroup(
            TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaDashDevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblLogo1)
                .addGap(8, 8, 8)
                .addComponent(jblNomeDev)
                .addGap(11, 11, 11)
                .addComponent(jblEquipe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblEquipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblCargo)
                .addGap(46, 46, 46)
                .addComponent(jblEscolha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnPyCharm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAndorid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIntellij, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVsCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEclipse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(TelaDashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnWebStorm, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXcode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPhpStorm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNetBeans, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualStudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        TelaDashDevLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAndorid, btnEclipse, btnIntellij, btnNetBeans, btnPhpStorm, btnPyCharm, btnVisualStudio, btnVsCode, btnWebStorm, btnXcode});

        DashDevTela.setLayer(TelaDashDev, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DashDevTelaLayout = new javax.swing.GroupLayout(DashDevTela);
        DashDevTela.setLayout(DashDevTelaLayout);
        DashDevTelaLayout.setHorizontalGroup(
            DashDevTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashDevTelaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TelaDashDev, javax.swing.GroupLayout.PREFERRED_SIZE, 1377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        DashDevTelaLayout.setVerticalGroup(
            DashDevTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaDashDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TelaDashDev.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout DashDevLayout = new javax.swing.GroupLayout(DashDev.getContentPane());
        DashDev.getContentPane().setLayout(DashDevLayout);
        DashDevLayout.setHorizontalGroup(
            DashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashDevTela)
        );
        DashDevLayout.setVerticalGroup(
            DashDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DashDevTela, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel1.setBackground(new java.awt.Color(206, 228, 217));
        jPanel1.setPreferredSize(new java.awt.Dimension(1368, 720));

        jblLogo2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jblLogo2.setForeground(new java.awt.Color(183, 51, 73));
        jblLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo2.setText("KEEPCODE");

        lblNomeIdeDtelhes.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        lblNomeIdeDtelhes.setForeground(new java.awt.Color(102, 102, 102));
        lblNomeIdeDtelhes.setText("Detalhes sobre:");

        lblDiscoDev.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblDiscoDev.setText("Disco");

        lblCpuDev.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblCpuDev.setText("CPU");

        lblRamDev.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblRamDev.setText("Ram");

        lblTempoUsoDev.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblTempoUsoDev.setText("Tempo de uso");

        lblgrafico.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblgrafico.setText("Uso do Disco");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setText("Uso da RAM");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setText("Tempo de Uso");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setText("Uso da CPU");

        lblNomeIde.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblNomeIde.setText("Disco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jblLogo2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDiscoDev)
                    .addComponent(lblgrafico)
                    .addComponent(jLabel9)
                    .addComponent(lblCpuDev))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblNomeIdeDtelhes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeIde)
                        .addContainerGap(489, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRamDev)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(lblTempoUsoDev, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(246, 246, 246))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblgrafico)
                                .addGap(4, 4, 4)
                                .addComponent(lblDiscoDev)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4)
                                .addComponent(lblRamDev)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTempoUsoDev)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpuDev))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jblLogo2)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeIdeDtelhes)
                            .addComponent(lblNomeIde))
                        .addGap(364, 364, 364)))
                .addGap(0, 235, Short.MAX_VALUE))
        );

        DashDetalhesDev.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DashDetalhesDevLayout = new javax.swing.GroupLayout(DashDetalhesDev);
        DashDetalhesDev.setLayout(DashDetalhesDevLayout);
        DashDetalhesDevLayout.setHorizontalGroup(
            DashDetalhesDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DashDetalhesDevLayout.setVerticalGroup(
            DashDetalhesDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout DetalheDevLayout = new javax.swing.GroupLayout(DetalheDev.getContentPane());
        DetalheDev.getContentPane().setLayout(DetalheDevLayout);
        DetalheDevLayout.setHorizontalGroup(
            DetalheDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
            .addGroup(DetalheDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DetalheDevLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DashDetalhesDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        DetalheDevLayout.setVerticalGroup(
            DetalheDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(DetalheDevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DetalheDevLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DashDetalhesDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(0, 204, 102));

        background.setBackground(new java.awt.Color(206, 228, 217));

        cardLogin.setBackground(new java.awt.Color(110, 150, 146));
        cardLogin.setForeground(new java.awt.Color(255, 102, 102));

        txtEmail.setBackground(new java.awt.Color(237, 230, 221));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(81, 78, 77));
        txtEmail.setText("Informe seu login aqui");
        txtEmail.setToolTipText("LOGIN");
        txtEmail.setNextFocusableComponent(txtSenha);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblValida.setBackground(new java.awt.Color(255, 51, 51));
        lblValida.setForeground(new java.awt.Color(255, 102, 102));
        lblValida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtSenha.setBackground(new java.awt.Color(237, 230, 221));
        txtSenha.setForeground(new java.awt.Color(81, 78, 77));
        txtSenha.setText("Senha123");
        txtSenha.setToolTipText("SENHA");
        txtSenha.setNextFocusableComponent(btnEntrar);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(136, 169, 167));
        btnEntrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(0, 0, 0));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblTitleLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitleLogin.setForeground(new java.awt.Color(81, 78, 77));
        lblTitleLogin.setText("FAÇA O LOGIN");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(81, 78, 77));
        lblEmail.setText("Login:");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(81, 78, 77));
        lblSenha.setText("Senha");

        javax.swing.GroupLayout cardLoginLayout = new javax.swing.GroupLayout(cardLogin);
        cardLogin.setLayout(cardLoginLayout);
        cardLoginLayout.setHorizontalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLoginLayout.createSequentialGroup()
                .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblSenha)
                            .addGroup(cardLoginLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitleLogin))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardLoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        cardLoginLayout.setVerticalGroup(
            cardLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLoginLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblTitleLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValida, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        txtEmail.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TelaLogin.setLayer(background, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout TelaLoginLayout = new javax.swing.GroupLayout(TelaLogin);
        TelaLogin.setLayout(TelaLoginLayout);
        TelaLoginLayout.setHorizontalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TelaLoginLayout.setVerticalGroup(
            TelaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TelaLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        Runtime.getRuntime().exit(0);
    }

    protected JDesktopPane getTelaLogin() {
        return TelaLogin;
    }


    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

//        this.dispose();
//        DashDev.setVisible(true);
        Conexao con = new Conexao();

        JdbcTemplate template = new JdbcTemplate(con.getBanco());

        List<Usuario.UsuarioDatas> pegandoUser = template.query("SELECT * FROM tb_us_dados WHERE us_login = ? AND us_senha = ?",
                new BeanPropertyRowMapper<>(Usuario.UsuarioDatas.class), txtEmail.getText(), txtSenha.getText());

        System.out.println(pegandoUser);
        String pegandoEmail = txtEmail.getText();
        String pegandoSenha = txtSenha.getText();

        String isAdmin = "1";

        GerandoLog teste = new GerandoLog();

        Usuario.UsuarioDatas userObj = new Usuario.UsuarioDatas();

        if (pegandoUser.isEmpty()) {

            lblValida.setText("Email ou senha incorretos");
            txtEmail.setText("Informe seu login aqui");
            txtSenha.setText("Senha123");

            try {
                teste.gravarLog("usuario nao encontrado");

            } catch (IOException ex) {

                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (pegandoUser.size() == 1) {

                for (Iterator<Usuario.UsuarioDatas> it = pegandoUser.iterator(); it.hasNext();) {

                    Usuario.UsuarioDatas tbUsDados = it.next();

                    if (tbUsDados.getUs_login().equals(pegandoEmail) && tbUsDados.getUs_senha().equals(pegandoSenha)) {

                        if (tbUsDados.getUs_is_adm()) {

                            // gestor entra aqui
                            this.setVisible(false);
                            this.dispose();
                            this.cpfGestor = tbUsDados.getId_cpf();
                            // AQUI TEM QUE IR O SELECT PARA PEGAR TODOS OS QUE O GESTOR COMANDA
                            DashGestor.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\resources\\logo-login.png"));
                            DashGestor.setVisible(true);
                            jblNomeGestor.setText(tbUsDados.getUs_nome_funcionario());
                            DashGestor.setDefaultCloseOperation(HIDE_ON_CLOSE);

                            userObj.setUs_nome_funcionario(tbUsDados.getUs_nome_funcionario());
                            userObj.setFk_id_empresa(tbUsDados.getFk_id_empresa());
                            userObj.setId_cpf(tbUsDados.getId_cpf());
                            userObj.setUs_cargo(tbUsDados.getUs_cargo());
                            userObj.setUs_login(tbUsDados.getUs_login());
                            userObj.setUs_senha(tbUsDados.getUs_senha());
                            userObj.setUs_is_adm(true);

                            try {
                                teste.gravarLog("login do gestor efetuado com sucesso");

                            } catch (IOException ex) {

                                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                            }

                        } else {

                            // dev entra aqui
                            this.setVisible(false);
                            this.dispose();
                            this.cpfDev = tbUsDados.getId_cpf();
                            
                            DashDev.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\resources\\logo-login.png"));
                            
                            DashDev.setVisible(true);
                            
                            jblNomeDev.setText(tbUsDados.getUs_nome_funcionario());
                            
//                            jblEquipe.setText(tbUsDados.getUs_equipe());
                            jblCargo.setText(tbUsDados.getUs_cargo());

                            List<TbUsMaquinaIdMaquina> sabendoIde = template.query("SELECT * FROM tb_us_ass_maquina WHERE tb_us_maquina_id_maquina = (SELECT DISTINCT id_maquina FROM tb_us_maquina WHERE fk_id_funcionario = ? AND tb_ide_maquina_id_ide = 9)",
                                    new BeanPropertyRowMapper<>(TbUsMaquinaIdMaquina.class), this.cpfDev);

                            List<String> nomesIde = new ArrayList<>();

                            nomesIde.add("1");// x code
                            nomesIde.add("2");// pycharm
                            nomesIde.add("3"); // vs code 
                            nomesIde.add("4");// netbBeans
                            nomesIde.add("5");// intejji
                            nomesIde.add("6");// android
                            nomesIde.add("7");// php
                            nomesIde.add("8");// webStrom
                            nomesIde.add("9");// eclipse
                            nomesIde.add("10");// visualStudio

                            for (Iterator<TbUsMaquinaIdMaquina> iterator = sabendoIde.iterator(); iterator.hasNext();) {
                                TbUsMaquinaIdMaquina next = iterator.next();

                                if (next.getTb_us_maquina_id_maquina().equals("1")) {
                                    btnXcode.setVisible(true);
                                } else if (next.getTb_us_maquina_id_maquina().equals("2")) {
                                    btnPyCharm.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("3")) {
                                    btnVsCode.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("4")) {
                                    btnNetBeans.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("5")) {
//                                    btn.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("6")) {
                                    btnAndorid.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("7")) {
                                    btnPhpStorm.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("8")) {
                                    btnWebStorm.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("9")) {
                                    btnEclipse.setVisible(true);

                                } else if (next.getTb_us_maquina_id_maquina().equals("10")) {
                                    btnVisualStudio.setVisible(true);

                                }
                            }

                            try {
                                teste.gravarLog("login do dev efetuado com sucesso");

                            } catch (IOException ex) {
                                Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);

                            }
                        }
                    }
                }

            } else if (pegandoUser.size()
                    > 1) {
                txtEmail.setText("Informe seu login aqui");
                txtSenha.setText("Senha123");
                lblValida.setText("Email ou senha incorretos:\n Login já utilizado!");

                try {
                    teste.gravarLog("login de usuario duplicado");

                } catch (IOException ex) {

                    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        int delay = 5000;   // tempo de espera antes da 1ª execução da tarefa.
        int interval = 1000;  // intervalo no qual a tarefa será executada.
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
//                System.out.println("Olá World!");
                KeepCodeAPI api = new KeepCodeAPI(userObj);

                api.chamandoProcessos(userObj);
            }
        }, delay, interval);

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void chamarTelaFuncionario(String nome) {

        GerandoLog gravandoLog = new GerandoLog();

        try {
            gravandoLog.gravarLog("gestor chamando dev");

        } catch (IOException ex) {

            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        Conexao con = new Conexao();

        JdbcTemplate template = new JdbcTemplate(con.getBanco());

        List<Usuario.UsuarioDatas> pegandoUser = template.query("SELECT * FROM tb_us_dados WHERE us_login = ?",
                new BeanPropertyRowMapper<>(Usuario.UsuarioDatas.class
                ), btnMaquina1.getText());

        System.out.println(pegandoUser);

        this.dispose();
        DashDev.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\resources\\logo-login.png"));
        DashDev.setVisible(true);

        for (Iterator<Usuario.UsuarioDatas> iterator = pegandoUser.iterator();
                iterator.hasNext();) {
            Usuario.UsuarioDatas usuarioDatas = iterator.next();
            this.cpfDev = usuarioDatas.getId_cpf();
            jblNomeDev.setText(usuarioDatas.getUs_nome_funcionario());
//            jblEquipe.setText(usuarioDatas.getUs_equipe());
            jblCargo.setText(usuarioDatas.getUs_cargo());
        }

        DashDev.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntrarMouseClicked

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        // TODO add your handling code here:
        if (txtSenha.getText().equals("")) {
            txtSenha.setText("Senha123");
        }
    }//GEN-LAST:event_txtSenhaFocusLost

//  PLACEHOLDER CAMPO SENHA    
    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        // TODO add your handling code here:
        if (txtSenha.getText().equals("Senha123")) {
            txtSenha.setText("");
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Informe seu login aqui");
        }
    }//GEN-LAST:event_txtEmailFocusLost

//    PLACEHOLDER CAMPO EMAIL
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if (txtEmail.getText().equals("Informe seu login aqui")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void btnMaquina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina1ActionPerformed
        chamarTelaFuncionario("note1");

    }//GEN-LAST:event_btnMaquina1ActionPerformed

    private void btnMaquina6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina6ActionPerformed
        chamarTelaFuncionario("note6");
    }//GEN-LAST:event_btnMaquina6ActionPerformed

    private void btnMaquina2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina2ActionPerformed
        chamarTelaFuncionario("note2");
    }//GEN-LAST:event_btnMaquina2ActionPerformed

    private void btnMaquina3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina3ActionPerformed
        chamarTelaFuncionario("note3");
    }//GEN-LAST:event_btnMaquina3ActionPerformed

    private void btnMaquina5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina5ActionPerformed
        chamarTelaFuncionario("note5");
    }//GEN-LAST:event_btnMaquina5ActionPerformed

    private void btnMaquina4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquina4ActionPerformed
        chamarTelaFuncionario("note4");

    }//GEN-LAST:event_btnMaquina4ActionPerformed

    private void btnAndoridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndoridActionPerformed

        chamarDetalhes("studio64", 6);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndoridActionPerformed

    private void btnVisualStudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualStudioActionPerformed
        chamarDetalhes("devenv", 10);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualStudioActionPerformed

    private void btnNetBeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetBeansActionPerformed
        chamarDetalhes("netbeans64", 4);
    }//GEN-LAST:event_btnNetBeansActionPerformed

    private void btnVsCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVsCodeActionPerformed
        chamarDetalhes("Code", 4);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnVsCodeActionPerformed

    private void btnWebStormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebStormActionPerformed
        chamarDetalhes("webstorm64", 8);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWebStormActionPerformed

    private void btnIntellijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntellijActionPerformed
        chamarDetalhes("idea64", 5);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnIntellijActionPerformed

    private void btnXcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXcodeActionPerformed
        chamarDetalhes("Xcode", 1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXcodeActionPerformed

    private void btnPhpStormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhpStormActionPerformed
        chamarDetalhes("phpstorm64", 7);
    }//GEN-LAST:event_btnPhpStormActionPerformed

    private void btnPyCharmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyCharmActionPerformed
        chamarDetalhes("pycharm64", 2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPyCharmActionPerformed

    private void btnEclipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEclipseActionPerformed
        chamarDetalhes("eclipse", 9);
    }//GEN-LAST:event_btnEclipseActionPerformed

    private void chamarDetalhes(String nome_ide, Integer id_ide) {

        GerandoLog gravandoLog = new GerandoLog();

        try {
            gravandoLog.gravarLog("dev chamando detalhe da ide");

        } catch (IOException ex) {

            Logger.getLogger(TelaLogin.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        Conexao con = new Conexao();
        JdbcTemplate template = new JdbcTemplate(con.getBanco());

        System.out.println(nome_ide);

        this.dispose();

        List<TbProcessosIde> ideDev = template.query("SELECT TOP 1 us_dt_hr_start_IDE, us_dt_hr_end_IDE, us_ide_ram, us_ide_cpu, us_ide_disco, us_ide_nome_processo FROM tb_processos_ide AS processo JOIN tb_us_maquina AS maq ON maq.id_maquina = processo.fk_id_maquina where us_ide_nome_processo = '" + nome_ide + "' AND fk_id_funcionario = ? ",
                new BeanPropertyRowMapper<>(TbProcessosIde.class
                ), this.cpfDev);

        System.out.println(ideDev);

        for (Iterator<TbProcessosIde> iterator = ideDev.iterator();
                iterator.hasNext();) {

            TbProcessosIde tbProcessosIde = iterator.next();

            String disco = Integer.toString(tbProcessosIde.getUs_ide_disco() / 1024 / 1024 / 1024);
            String cpu = Integer.toString(tbProcessosIde.getUs_ide_cpu());
            String ram = Integer.toString(tbProcessosIde.getUs_ide_ram());

            lblCpuDev.setText(cpu + "%");
            lblDiscoDev.setText(disco + "%");
            lblRamDev.setText(ram + "%");
            lblNomeIde.setText(tbProcessosIde.getUs_ide_nome_processo());

        }

        DetalheDev.setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\resources\\logo-login.png"));
        DetalheDev.setVisible(true);

        DetalheDev.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("src\\main\\resources\\logo-login.png"));
    }

    public static void main(String args[]) throws IOException {

        if (!SystemTray.isSupported()) {
            System.out.println("sistema não suportado !!!!");
            return;
        }
        //get the systemTray of the system
        SystemTray systemTray = SystemTray.getSystemTray();

        //Toolkit.getDefaultToolkit().getImage("src/resources/busylogo.jpg");
        Image image = Toolkit.getDefaultToolkit().getImage("src\\main\\resources\\logo-login.png");

        //popupmenu
        PopupMenu trayPopupMenu = new PopupMenu();

        //1t menu item for popupmenu
        MenuItem action = new MenuItem("Abrir tela");

        GerandoLog gravandoLog = new GerandoLog();

        action.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                JOptionPane.showMessageDialog(null, "teste de click");

                try {
                    gravandoLog.gravarLog("iniciando aplicação keep code");

                } catch (IOException ex) {

                    Logger.getLogger(TelaLogin.class
                            .getName()).log(Level.SEVERE, null, ex);
                }

                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;

                        }
                    }

                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(TelaLogin.class
                            .getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                    new TelaLogin().setVisible(true);
                });

                try {
                    gravandoLog.gravarLog("finalizando aplicação");

                } catch (IOException ex) {
                    Logger.getLogger(TelaLogin.class
                            .getName()).log(Level.SEVERE, null, ex);

                }

            }
        });
        trayPopupMenu.add(action);

        //2nd menuitem of popupmenu
        MenuItem close = new MenuItem("fechar");
        close.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    gravandoLog.gravarLog("finalizando aplicação");

                } catch (IOException ex) {
                    Logger.getLogger(TelaLogin.class
                            .getName()).log(Level.SEVERE, null, ex);

                }
                System.exit(0);
            }
        });

        trayPopupMenu.add(close);

        //setting tray icon
        TrayIcon trayIcon = new TrayIcon(image, "KCODE", trayPopupMenu);
        //adjust to default size as per system recommendation 
        trayIcon.setImageAutoSize(true);

        try {
            systemTray.add(trayIcon);
        } catch (AWTException awtException) {
            awtException.printStackTrace();
        }
        System.out.println("olhe a sua barra de tarefas ;)");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DashDetalhesDev;
    private javax.swing.JFrame DashDev;
    private javax.swing.JDesktopPane DashDevTela;
    private javax.swing.JFrame DashGestor;
    private javax.swing.JFrame DetalheDev;
    private javax.swing.JPanel TelaDashDev;
    private javax.swing.JDesktopPane TelaDashGestor;
    private javax.swing.JDesktopPane TelaLogin;
    private javax.swing.JPanel background;
    private javax.swing.JButton btnAndorid;
    private javax.swing.JButton btnEclipse;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnIntellij;
    private javax.swing.JButton btnMaquina1;
    private javax.swing.JButton btnMaquina2;
    private javax.swing.JButton btnMaquina3;
    private javax.swing.JButton btnMaquina4;
    private javax.swing.JButton btnMaquina5;
    private javax.swing.JButton btnMaquina6;
    private javax.swing.JButton btnNetBeans;
    private javax.swing.JButton btnPhpStorm;
    private javax.swing.JButton btnPyCharm;
    private javax.swing.JButton btnVisualStudio;
    private javax.swing.JButton btnVsCode;
    private javax.swing.JButton btnWebStorm;
    private javax.swing.JButton btnXcode;
    private javax.swing.JPanel cardLogin;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblBemVindo;
    private javax.swing.JLabel jblCargo;
    private javax.swing.JLabel jblEmpresa;
    private javax.swing.JLabel jblEquipe;
    private javax.swing.JLabel jblEquipe1;
    private javax.swing.JLabel jblEscolha;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel jblLogo1;
    private javax.swing.JLabel jblLogo2;
    private javax.swing.JLabel jblMaquinaa;
    private javax.swing.JLabel jblNomeDev;
    private javax.swing.JLabel jblNomeGestor;
    private javax.swing.JPanel jpFundo;
    private javax.swing.JLabel lblCpuDev;
    private javax.swing.JLabel lblDiscoDev;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGestorEquipe;
    private javax.swing.JLabel lblNomeIde;
    private javax.swing.JLabel lblNomeIdeDtelhes;
    private javax.swing.JLabel lblRamDev;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTempoUsoDev;
    private javax.swing.JLabel lblTitleLogin;
    private javax.swing.JLabel lblValida;
    private javax.swing.JLabel lblgrafico;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

}
